AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation Template for Managed Grafana
Parameters:
  Name:
    Description: |
      (Required) Name for each resources lowercase prefix.
    Type: String
    Default: amp-amg-recap2022
  EmailAddress:
    Description: |
      (Required) Email address for SNS subscription.
    Type: String
Resources:
# AMG #
  AmazonGrafanaWorkspaceAOSPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${Name}-AmazonGrafanaWorkspaceAOSPolicy
      Roles: 
        - !Ref AmazonGrafanaWorkspaceIAMRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'es:ESHttpGet'
              - 'es:DescribeElasticsearchDomains'
              - 'es:ListDomainNames'
            Resource: '*'
          - Effect: Allow
            Action:
              - 'es:ESHttpPost'
            Resource: 
              - 'arn:aws:es:*:*:domain/*/_msearch*'
              - 'arn:aws:es:*:*:domain/*/_opendistro/_ppl'

  AmazonGrafanaWorkspaceCloudWatchPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${Name}-AmazonGrafanaWorkspaceCloudWatchPolicy
      Roles: 
        - !Ref AmazonGrafanaWorkspaceIAMRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'cloudwatch:DescribeAlarmsForMetric'
              - 'cloudwatch:DescribeAlarmHistory'
              - 'cloudwatch:DescribeAlarms'
              - 'cloudwatch:ListMetrics'
              - 'cloudwatch:GetMetricStatistics'
              - 'cloudwatch:GetMetricData'
              - 'cloudwatch:GetInsightRuleReport'
              - 'logs:DescribeLogGroups'
              - 'logs:GetLogGroupFields'
              - 'logs:StartQuery'
              - 'logs:StopQuery'
              - 'logs:GetQueryResults'
              - 'logs:GetLogEvents'
              - 'ec2:DescribeTags'
              - 'ec2:DescribeInstances'
              - 'ec2:DescribeRegions'
              - 'tag:GetResources'
            Resource: '*'

  AmazonGrafanaWorkspacePrometheusPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${Name}-AmazonGrafanaWorkspacePrometheusPolicy
      Roles: 
        - !Ref AmazonGrafanaWorkspaceIAMRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'aps:ListWorkspaces'
              - 'aps:DescribeWorkspace'
              - 'aps:QueryMetrics'
              - 'aps:GetLabels'
              - 'aps:GetSeries'
              - 'aps:GetMetricMetadata'
              - 'aps:ListRules'
              - 'aps:ListAlertManagerSilences'
              - 'aps:ListAlertManagerAlerts'
              - 'aps:GetAlertManagerStatus'
              - 'aps:ListAlertManagerAlertGroups'
              - 'aps:PutAlertManagerSilences'
              - 'aps:AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation Template for Managed Grafana
Parameters:
  Name:
    Description: |
      (Required) Name for each resources lowercase prefix.
    Type: String
    Default: amp-amg-recap
  
  EmailAddress:
    Description: |
      (Required) Email address for SNS subscription.
    Type: String
Resources:
# AMG #
  AmazonGrafanaWorkspaceAOSPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${Name}-AmazonGrafanaWorkspaceAOSPolicy
      Roles: 
        - !Ref AmazonGrafanaWorkspaceIAMRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'es:ESHttpGet'
              - 'es:DescribeElasticsearchDomains'
              - 'es:ListDomainNames'
            Resource: '*'
          - Effect: Allow
            Action:
              - 'es:ESHttpPost'
            Resource: 
              - 'arn:aws:es:*:*:domain/*/_msearch*'
              - 'arn:aws:es:*:*:domain/*/_opendistro/_ppl'

  AmazonGrafanaWorkspaceCloudWatchPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${Name}-AmazonGrafanaWorkspaceCloudWatchPolicy
      Roles: 
        - !Ref AmazonGrafanaWorkspaceIAMRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'cloudwatch:DescribeAlarmsForMetric'
              - 'cloudwatch:DescribeAlarmHistory'
              - 'cloudwatch:DescribeAlarms'
              - 'cloudwatch:ListMetrics'
              - 'cloudwatch:GetMetricStatistics'
              - 'cloudwatch:GetMetricData'
              - 'cloudwatch:GetInsightRuleReport'
              - 'logs:DescribeLogGroups'
              - 'logs:GetLogGroupFields'
              - 'logs:StartQuery'
              - 'logs:StopQuery'
              - 'logs:GetQueryResults'
              - 'logs:GetLogEvents'
              - 'ec2:DescribeTags'
              - 'ec2:DescribeInstances'
              - 'ec2:DescribeRegions'
              - 'tag:GetResources'
            Resource: '*'

  AmazonGrafanaWorkspacePrometheusPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${Name}-AmazonGrafanaWorkspacePrometheusPolicy
      Roles: 
        - !Ref AmazonGrafanaWorkspaceIAMRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'aps:ListWorkspaces'
              - 'aps:DescribeWorkspace'
              - 'aps:QueryMetrics'
              - 'aps:GetLabels'
              - 'aps:GetSeries'
              - 'aps:GetMetricMetadata'
              - 'aps:ListRules'
              - 'aps:ListAlertManagerSilences'
              - 'aps:ListAlertManagerAlerts'
              - 'aps:GetAlertManagerStatus'
              - 'aps:ListAlertManagerAlertGroups'
              - 'aps:PutAlertManagerSilences'
              - 'aps:DeleteAlertManagerSilence'
            Resource: '*'

  AmazonGrafanaWorkspaceSNSPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${Name}-AmazonGrafanaWorkspaceSNSPolicy
      Roles: 
        - !Ref AmazonGrafanaWorkspaceIAMRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'sns:Publish'
            Resource: !Sub "arn:aws:sns:*:${AWS::AccountId}:grafana*"

  AmazonGrafanaWorkspaceIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${Name}-AmazonGrafanaWorkspaceIAMRole
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AWSXrayReadOnlyAccess'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - grafana.amazonaws.com
            Action:
              - 'sts:AssumeRole'

  AmazonGrafanaWorkspace:
    Type: AWS::Grafana::Workspace
    Properties:
      AccountAccessType: CURRENT_ACCOUNT
      AuthenticationProviders:
        - AWS_SSO
      Name: !Sub ${Name}-AmazonGrafanaWorkspace
      Description: Amazon Grafana Workspace
      PermissionType: CUSTOMER_MANAGED
      RoleArn: !GetAtt 
        - AmazonGrafanaWorkspaceIAMRole
        - Arn

  SNSTopic:
   Type: AWS::SNS::Topic
   Properties:
     TopicName: !Sub grafana-${Name}-topic
     Subscription:
       - Endpoint: !Ref EmailAddress
         Protocol: emails'
            Resource: '*'

  AmazonGrafanaWorkspaceSNSPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${Name}-AmazonGrafanaWorkspaceSNSPolicy
      Roles: 
        - !Ref AmazonGrafanaWorkspaceIAMRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'sns:Publish'
            Resource: !Sub "arn:aws:sns:*:${AWS::AccountId}:grafana*"

  AmazonGrafanaWorkspaceIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${Name}-AmazonGrafanaWorkspaceIAMRole
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AWSXrayReadOnlyAccess'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - grafana.amazonaws.com
            Action:
              - 'sts:AssumeRole'

  AmazonGrafanaWorkspace:
    Type: AWS::Grafana::Workspace
    Properties:
      AccountAccessType: CURRENT_ACCOUNT
      AuthenticationProviders:
        - AWS_SSO
      Name: !Sub ${Name}-AmazonGrafanaWorkspace
      Description: Amazon Grafana Workspace
      PermissionType: CUSTOMER_MANAGED
      RoleArn: !GetAtt 
        - AmazonGrafanaWorkspaceIAMRole
        - Arn

  SNSTopic:
   Type: AWS::SNS::Topic
   Properties:
     TopicName: !Sub grafana-${Name}-topic
     Subscription:
       - Endpoint: !Ref EmailAddress
         Protocol: email
